# modified from https://github.com/input-output-hk/cardano-addresses/blob/master/.github/workflows/main.yml
name: Haskell CI - Stack

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest]
        # use this to specify what resolvers and ghc to use
        stack-yaml: 
          - "--stack-yaml=stack-8.4.4.yaml"
          - "--stack-yaml=stack-8.6.5.yaml"
          - "--stack-yaml=stack-8.8.4.yaml"
          - "--stack-yaml=stack-8.10.4.yaml"

    runs-on: ${{ matrix.os }}
    steps:  
    
    - name: 👺 GitHub actions env workaround
      run: 'echo "ACTIONS_ALLOW_UNSECURE_COMMANDS=true" >> $GITHUB_ENV'
      
    - name: 💽 Install OS Packages
      uses: mstksg/get-package@v1

    - name: 📥 Checkout repository
      uses: actions/checkout@v1

    - name: 🧰 Setup stack
      uses: mstksg/setup-stack@v1

    - name: 💾 Cache Dependencies
      id: cache
      uses: actions/cache@v1
      with:
        path: ~/.stack
        key: ${{ matrix.os }}-${{ hashFiles('stack.yaml') }}

    - name: 📸 Build Snapshot
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        stack --no-terminal $ARGS build --bench --only-snapshot
      env:
        ARGS: ${{ matrix.stack-yaml }}

    - name: 🔨 Build & Test 
      run: | 
        stack $ARGS build --no-terminal --bench --haddock --no-haddock-deps --no-run-benchmarks
        stack $ARGS test lsp-test:tests --no-terminal --bench --haddock --no-haddock-deps --no-run-benchmarks
      env:
        ARGS: ${{ matrix.stack-yaml }}