name: Haskell CI (Stack)

on: [push, pull_request]




jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        # os: [ubuntu-latest, macOS-latest, windows-latest]
        # use this to specify what resolvers and ghc to use
        stack-yaml: ["--stack-yaml=stack-8.4.4.yaml"]

    runs-on: ${{ matrix.os }}
    steps:  
    
    - name: 'GitHub actions env workaround'
      run: 'echo "ACTIONS_ALLOW_UNSECURE_COMMANDS=true" >> $GITHUB_ENV'
      
    - name: Install OS Packages
      uses: mstksg/get-package@v1

    - uses: actions/checkout@v1

    - name: Setup stack
      uses: mstksg/setup-stack@v1

    - name: Install dependencies
      run: stack --no-terminal --install-ghc $ARGS test --bench --only-dependencies
      env:
        ARGS: ${{ matrix.stack-yaml }}

    - name: Build
      run: stack --no-terminal $ARGS test --bench --no-run-benchmarks --haddock --no-haddock-deps
      env:
        ARGS: ${{ matrix.stack-yaml }}
