name: Haskell CI - Stack (Windows)

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        # use this to specify what resolvers and ghc to use
        stack-yaml: 
          - "--stack-yaml=stack-8.4.4.yaml"
          - "--stack-yaml=stack-8.6.5.yaml"
          - "--stack-yaml=stack-8.8.3.yaml"
          - "--stack-yaml=stack-8.10.4.yaml"

    runs-on: ${{ matrix.os }}
    steps:
    - name: 👺 GitHub actions env workaround
      run: 'echo "ACTIONS_ALLOW_UNSECURE_COMMANDS=true" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append'

    - name: 📥 Checkout repository
      uses: actions/checkout@v1

    - name: 🧰 Setup Stack
      uses: mstksg/setup-stack@69e4283faeb7a89f26326daa36e9cc0fa7a023bd

    - name: 💾 Cache Dependencies
      id: cache
      uses: actions/cache@v1
      with:
        path: ~/.stack
        key: ${{ matrix.os }}-${{ hashFiles('stack.yaml') }}

    - name: 📸 Build Snapshot
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        curl -O http://repo.msys2.org/msys/x86_64/msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz
        curl -O http://repo.msys2.org/msys/x86_64/msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz.sig
        stack --no-terminal exec -- pacman -U --noconfirm msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz
        stack --no-terminal exec -- pacman -Syu --no-confirm
        stack --no-terminal exec -- pacman -S --noconfirm mingw-w64-x86_64-pcre
        stack --no-terminal exec -- pacman -S --noconfirm mingw-w64-x86_64-pkg-config
        stack --no-terminal $ARGS build --bench --only-snapshot
      env:
        ARGS: ${{ matrix.stack-yaml }}

    - name: 🔨 Build (no testing)
      run: | 
        stack --no-terminal $ARGS build --bench --haddock --no-haddock-deps --no-run-benchmarks
      env:
        ARGS: ${{ matrix.stack-yaml }}